# Generated by Django 5.2.5 on 2025-09-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(default='Unkown', max_length=100)),
                ('book_autor', models.CharField(default='Unkown', max_length=100)),
                ('isbn_num', models.CharField(max_length=13, unique=True)),
                ('book_price', models.DecimalField(decimal_places=2, default=0, max_digits=17)),
                ('borrow_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_avalible', models.BooleanField(default=True)),
                ('copies', models.IntegerField(default=1)),
            ],
        ),
    ]
