# Generated by Django 5.2.5 on 2025-09-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_borrow_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow_book',
            name='book_title',
            field=models.CharField(default='Unkown', max_length=100),
        ),
    ]
