# Generated by Django 5.2.5 on 2025-09-10 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_borrow_book_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='borrow_price',
        ),
    ]
