# Generated by Django 5.2.5 on 2025-09-10 10:49

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_remove_book_borrow_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow_book',
            name='panalty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='borrow_book',
            name='return_date',
            field=models.DateTimeField(default=datetime.date(2025, 9, 13)),
        ),
    ]
