# Generated by Django 5.2.5 on 2025-09-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0008_alter_borrow_book_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow_book',
            name='penaly_per_day',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=20),
        ),
    ]
