# Generated by Django 5.2.5 on 2025-09-19 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0011_alter_borrow_book_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow_book',
            name='return_date',
            field=models.DateTimeField(default=datetime.date(2025, 9, 19)),
        ),
    ]
