# Generated by Django 5.2.5 on 2025-09-23 10:56

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0015_alter_borrow_book_return_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow_book',
            old_name='panalty',
            new_name='penalty',
        ),
        migrations.RenameField(
            model_name='borrow_book',
            old_name='penaly_per_day',
            new_name='penalty_per_day',
        ),
        migrations.AddField(
            model_name='borrow_book',
            name='penalty_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_autor',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_title',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='borrow_book',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.book'),
        ),
        migrations.AlterField(
            model_name='borrow_book',
            name='book_title',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='borrow_book',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 30, 10, 56, 23, 503984, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='borrow_book',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
