# Generated by Django 5.2.5 on 2025-09-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactus_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.BigIntegerField(max_length=10, unique=True),
        ),
    ]
